name: Build and Push Docker Image on Release

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    concurrency:
      group: docker

    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract release version
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=sha

    - name: Set lowercase repository name
      run: |
        echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/${{ env.REPO_LC }}:${{ steps.meta.outputs.version }}
          ghcr.io/${{ env.REPO_LC }}:${{ steps.meta.outputs.major }}
          ghcr.io/${{ env.REPO_LC }}:${{ steps.meta.outputs.major }}.${{ steps.meta.outputs.minor }}
          ghcr.io/${{ env.REPO_LC }}:${{ steps.meta.outputs.sha }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: index.docker.io/edgurgel/poxa-automated
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
